version: 1.0.{build}
image: Ubuntu
build_script:
- sh: >-
    sudo apt update --fix-missing
    
    sudo apt install -y libmicrohttpd-dev clang libboost-all-dev libmysqlclient-dev libssl-dev

    cd ./src/WebAPI/PartyOrganizer.WebAPI
    make
