version: 1.0.{build}
image: Ubuntu
build_script:
- sh: >-
    sudo apt update --fix-missing
    sudo apt install -y libmicrohttpd-dev clang libboost-all-dev libmysqlclient-dev libssl-dev

    clang++ -std=c++14 -ftemplate-depth=1024 ./src/WebAPI/PartyOrganizer.WebAPI/*.cpp ./src/WebAPI/PartyOrganizer.WebAPI/Services/*.cpp -I ./src/WebAPI/PartyOrganizer.WebAPI/include -L ./src/WebAPI/PartyOrganizer.WebAPI/libs -lmicrohttpd -lmysqlclient -lcrypto -lpthread
