// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_get_user
#define IOD_SYMBOL_get_user
    iod_define_symbol(get_user)
#endif

#ifndef IOD_SYMBOL_hello
#define IOD_SYMBOL_hello
    iod_define_symbol(hello)
#endif

#ifndef IOD_SYMBOL_delete_user
#define IOD_SYMBOL_delete_user
    iod_define_symbol(delete_user)
#endif

#ifndef IOD_SYMBOL_message
#define IOD_SYMBOL_message
    iod_define_symbol(message)
#endif

#ifndef IOD_SYMBOL_create_user
#define IOD_SYMBOL_create_user
    iod_define_symbol(create_user)
#endif

#ifndef IOD_SYMBOL_date
#define IOD_SYMBOL_date
    iod_define_symbol(date)
#endif

#ifndef IOD_SYMBOL_primary_key
#define IOD_SYMBOL_primary_key
    iod_define_symbol(primary_key)
#endif

#ifndef IOD_SYMBOL_username
#define IOD_SYMBOL_username
    iod_define_symbol(username)
#endif

#ifndef IOD_SYMBOL_password
#define IOD_SYMBOL_password
    iod_define_symbol(password)
#endif

#ifndef IOD_SYMBOL_alias
#define IOD_SYMBOL_alias
    iod_define_symbol(alias)
#endif

#ifndef IOD_SYMBOL_text
#define IOD_SYMBOL_text
    iod_define_symbol(text)
#endif

#ifndef IOD_SYMBOL_update_user
#define IOD_SYMBOL_update_user
    iod_define_symbol(update_user)
#endif

#ifndef IOD_SYMBOL_token
#define IOD_SYMBOL_token
    iod_define_symbol(token)
#endif

#ifndef IOD_SYMBOL_generate
#define IOD_SYMBOL_generate
    iod_define_symbol(generate)
#endif

#ifndef IOD_SYMBOL_validate
#define IOD_SYMBOL_validate
    iod_define_symbol(validate)
#endif

#ifndef IOD_SYMBOL_valid
#define IOD_SYMBOL_valid
    iod_define_symbol(valid)
#endif

#ifndef IOD_SYMBOL_id
#define IOD_SYMBOL_id
    iod_define_symbol(id)
#endif

#ifndef IOD_SYMBOL_maxUsers
#define IOD_SYMBOL_maxUsers
    iod_define_symbol(maxUsers)
#endif

#ifndef IOD_SYMBOL_status
#define IOD_SYMBOL_status
    iod_define_symbol(status)
#endif

#ifndef IOD_SYMBOL_auto_increment
#define IOD_SYMBOL_auto_increment
    iod_define_symbol(auto_increment)
#endif

#ifndef IOD_SYMBOL_media
#define IOD_SYMBOL_media
    iod_define_symbol(media)
#endif

#ifndef IOD_SYMBOL_extension
#define IOD_SYMBOL_extension
    iod_define_symbol(extension)
#endif

#ifndef IOD_SYMBOL_name
#define IOD_SYMBOL_name
    iod_define_symbol(name)
#endif

#ifndef IOD_SYMBOL_complexity
#define IOD_SYMBOL_complexity
    iod_define_symbol(complexity)
#endif

#ifndef IOD_SYMBOL_description
#define IOD_SYMBOL_description
    iod_define_symbol(description)
#endif

#ifndef IOD_SYMBOL_state
#define IOD_SYMBOL_state
    iod_define_symbol(state)
#endif

#ifndef IOD_SYMBOL_dateEnds
#define IOD_SYMBOL_dateEnds
    iod_define_symbol(dateEnds)
#endif

#ifndef IOD_SYMBOL_dateCreated
#define IOD_SYMBOL_dateCreated
    iod_define_symbol(dateCreated)
#endif

#ifndef IOD_SYMBOL_completition
#define IOD_SYMBOL_completition
    iod_define_symbol(completition)
#endif

#ifndef IOD_SYMBOL_dateStarts
#define IOD_SYMBOL_dateStarts
    iod_define_symbol(dateStarts)
#endif

#ifndef IOD_SYMBOL_minUsers
#define IOD_SYMBOL_minUsers
    iod_define_symbol(minUsers)
#endif

