// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_hello
#define IOD_SYMBOL_hello
    iod_define_symbol(hello)
#endif

#ifndef IOD_SYMBOL_message
#define IOD_SYMBOL_message
    iod_define_symbol(message)
#endif

#ifndef IOD_SYMBOL_password
#define IOD_SYMBOL_password
    iod_define_symbol(password)
#endif

#ifndef IOD_SYMBOL_token
#define IOD_SYMBOL_token
    iod_define_symbol(token)
#endif

#ifndef IOD_SYMBOL_username
#define IOD_SYMBOL_username
    iod_define_symbol(username)
#endif

